### PR TITLE
Julia 0.5

### PR DESCRIPTION
**Pull request by meggart**
Hi @hans-permana 

I managed to successfully build the image on my Laptop, so this should work now...

### CODE REVIEW

**Comment by hans-permana** [comment]
@meggart Hi Fabian, I have installed this image in the cluster (by manually changing the Dockerfile and use docker build command). Could you have a try and see if everything works as expected? After you verify, I will merge this pull request and rebuild this image in the Dockerhub.

**Comment by meggart** [comment]
There was still one bug, I think with this change it should work.

**Comment by hans-permana** [comment]
@meggart I have rebuilt the container. Could you test again?

**Comment by meggart** [comment]
Yes this works now. I did another update, so that an R Kernel and the R bindings are installed, too. COuld you please build again?

**Comment by hans-permana** [comment]
Hi @meggart,

I have rebuilt the image again. Can you do a quick check before I merge this PR?

**Comment by meggart** [comment]
Hi Hans, 
thanks for rebuilding. Somehow the R notebooks don't work yet. When I try to launch an R notebook and execute a line, the kernel will die. I can't see the debug output, so I don't know what happens. 

The R installation seems to have worked, I can successfully execute R code from a Julia notebook (through RCall), so there must be some problem in the jupyter <--> R communication.

**Comment by hans-permana** [comment]
Hi @meggart,

Here is the error that was produced when running the R command:

```
Error in .External2(C_X11, paste("png::", filename, sep = ""), g$width,  :                 
  unable to start device PNG                                                               
Calls: <Anonymous> ... evaluate -> dev.new -> do.call -> <Anonymous> -> ok_device          
In addition: Warning message:                                                              
In ok_device(filename, ...) : unable to open connection to X11 display ''                  
Execution halted                                                                           
[I 2016-11-10 08:48:29.416 meggart restarter:103] KernelRestarter: restarting kernel (1/5) 
WARNING:root:kernel 2a987689-9e5e-4f47-b1bf-49246a19f5f5 restarted                         
```

And I stumbled on this similar issue https://github.com/jupyter/notebook/issues/1775. Do you think the proposed solution makes sense?

**Comment by meggart** [comment]
Yes, this solution might work. I don't exactly know which R version is installed through conda and if it is built with Cairo, we could try. Otherwise we could install R through apt-get first and then install the irkernel.

**Comment by meggart** [comment]
BTW is there a (simple) way for me to test these docker images that I buil?

**Review by hans-permana — APPROVED** [review]

**Pull request merged**
